### ISSUE TITLE
Re-introduce Disqus comments

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-website#10]
... or not. They're gone now (on the new Jekyll-based site). Not sure it's worth re-introducing them. May want to just send folks to Twitter / Forum for following up on posts, in the interest of consolidating communication channels.

**Comment by ManfredKarrer** [comment]
I don't see much value in Disqus. We can drop it. Often comments have been rather spam/reddit-like trolling...

**Comment by cbeams** [comment]
Sounds good. Closing as dropped, thanks.
