### ISSUE TITLE
Update fee docs

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#109]
The 2 proposals for simplifying the fee model and reducing the maker fee have been approved and PRs are pending and intended to get into the upcoming release (around 8-9.1.2019).
@m52go Could you please update the FAQ (and if the fee model is decribed elsewhere - not aware myself of any other place though).

- Market price based caclulation is removed. Maker fee is now simply 0,1% of trade amount but min. fee is 0.00005 BTC.  
- Taker fee is now 0,3 % (instead of 0,2%).

**Comment by m52go** [comment]
Completed with #111.
