### ISSUE TITLE
Markets page not loading all trades by default and currency pairs are not loading on update.

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq-website#113]
https://bisq.network/markets/?currency=btc_usd

![screen shot 2019-01-20 at 4 27 48 pm](https://user-images.githubusercontent.com/807505/51445325-b3b16200-1cd1-11e9-9cfa-a46af9d94b35.png)

![screen shot 2019-01-20 at 4 38 25 pm](https://user-images.githubusercontent.com/807505/51445348-e52a2d80-1cd1-11e9-8d3d-7f0ab67111da.png)

![screen shot 2019-01-20 at 4 38 35 pm](https://user-images.githubusercontent.com/807505/51445353-ea877800-1cd1-11e9-8d81-c10cf7b552be.png)

https://markets.bisq.network/api/hloc?market=btc_usd&timestamp=no&interval=minute&timestamp_from=&timestamp_to=&format=jscallback&callback=jQuery33106472370186256875_1548020274906&_=1548020274907
{ "success": 0, "error": "An unexpected error occurred." }

**Comment by ManfredKarrer** [comment]
I will look into it.

**Comment by ManfredKarrer** [comment]
Fixed, was out of memory issues.
