### ISSUE TITLE
Unable to detect current (active) main nav item

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq-website#114]
In bisq-website/_includes/main_nav.html we should be able to print a “current” class if the path matches the url.

![screen shot 2019-01-20 at 4 42 36 pm](https://user-images.githubusercontent.com/807505/51445417-8a450600-1cd2-11e9-9dd1-6d65a8f0db5d.png)

Can we add slashes on bisq-website/_data/main_nav.yml to the end of each link so the comparison matches a result?

**Comment by ManfredKarrer** [comment]
@m52go I leave that to you

**Comment by m52go** [comment]
Fixed with #116.
