### ISSUE TITLE
Page should load with "All" and on change, selected pair should be the selected option.

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq-website#115]
I'm not sure what happened but this used to be working.

When user loads page it should read "All" in the field and "All" should remain as the first option.

After the user selects a different option, the page should refresh and the selected option should be fetch from the URL parameter.

<img width="626" alt="screenshot at jan 21 21-11-28" src="https://user-images.githubusercontent.com/807505/51507985-6e6c5d80-1dc1-11e9-9e89-f2ffc74ef758.png">

**Comment by m52go** [comment]
Will take a look. I remember this working as well...

**Comment by m52go** [comment]
Fixed with #116.
