### ISSUE TITLE
consider using privacy and freedom respecting applications for project communication

### ISSUE THREAD

**Issue by ITwrx** [bisq-network/bisq-website#119]
please consider migrating to (or at least offering the alternative of) privacy and freedom respecting communications applications. The proprietary, centralized, data-mining applications currently listed on the bisq website for project communication should be contrary to bisq's goals and desired public image. i understand if the project feels the need to also advertise on establishment platforms, but there's no need for those to be the recommended and promoted channels, imho.

github? gitea or similar or at least (opencore) gitlab.
twitter? self hosted fediverse/activitypub application. pleroma, mastadon, osada, etc.
youtube? lbry.io, bittube, peertube
slack? rocketchat, mattermost, osada
reddit: many FOSS options for posting articles with comments.

thanks

**Comment by ManfredKarrer** [comment]
Agree, its just a question of resources and time....

We are in the process to move to rocketchat. 
To get away from Github is also on our roadmap but no resources atm for that. 
With regard to social media: We might get rid of any "official" account some day or leave it completely to Bisq uses to run those (like the Telegram group).

**Comment by ITwrx** [comment]
what are the plans for github migration/what is needed?
re: letting social media be handled by the community: i didn't even think about that. that's not a bad idea as long as there's somewhere to coordinate the marketing operation(like rocketchat).

**Comment by ManfredKarrer** [comment]
We have not started yet with GH migration as too much else on the table...

**Comment by ITwrx** [comment]
right, i understood that you hadn't started yet. i was just wondering what resources were needed in case there was some critical bike shedding that needed to be done. :) or maybe something i could help with.

**Comment by ManfredKarrer** [comment]
Thanks for your offer! Lets get back to that after the DAO launch. Migrating from Github is a serious step which I cannot delegate completely - so I will need to spend some time on it as well and the day only has 24 hours ;-).

**Comment by alphaonion** [comment]
Also, The bisq clearnet website/pages need to reachable via onion in case of dns/isp takedown.  This needs to happen rather quickly as well!

**Comment by m52go** [comment]
Website is a git repository and documentation is self-hosted...so in case of a DNS issue, the data should be safe. I'm not sure it makes sense to make the websites available at onion addresses at this point.

**Comment by m52go** [comment]
Closing this issue since it's not particularly relevant to the website. Further discussion is probably better off at https://github.com/bisq-network/bisq/discussions anyway.
