### ISSUE TITLE
Use Red Hat or Fedora inspired image for the rpm download item in the dropdown

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq-website#125]
Would be nice to have a Red Hat or Fedora inspired image for the rpm download item in the dropdown, rather than using the generic Linux icon:
![image](https://user-images.githubusercontent.com/603793/53206630-58330680-35e6-11e9-99eb-d46b405d0f99.png)

**Comment by huey735** [comment]
@devinbileck what do you think of this?

![redhat-g](https://user-images.githubusercontent.com/44140017/59134448-21a1b180-8973-11e9-88a8-fed4916d19e3.jpg)

**Comment by devinbileck** [comment]
Not bad. But perhaps should take inspiration from their new simplified icon with just the hat?
![image](https://user-images.githubusercontent.com/603793/59138955-ea1c1080-8944-11e9-96ca-4b661f540b70.png)

**Comment by devinbileck** [comment]
Also, perhaps we should redo the Ubuntu icon as a Debian icon so as to represent the base distro from which Ubuntu is based on (or other distros that are based on it). For example, taking inspiration from:
![image](https://user-images.githubusercontent.com/603793/59139002-323b3300-8945-11e9-9265-8b4bcfa79a42.png)

And while we are at it, may want to do an Arch icon based on:
![image](https://user-images.githubusercontent.com/603793/59139005-38c9aa80-8945-11e9-9bfc-5071464404b2.png)

**Comment by huey735** [comment]
Take a look. I prefer Ubuntu's logo over Debian's as the positive-negative space are more balanced.
![linux-distros-2](https://user-images.githubusercontent.com/44140017/59141519-25026080-89a6-11e9-8ac7-8151df439bfd.png)

**Comment by devinbileck** [comment]
Looks good!
I do agree regarding the positive-negative space. However, I like the idea of using Debian for consistency as the base distro. Although, I suppose we could use Ubuntu and switch to the Fedora logo for the most "popular" distros that use those packages?

**Comment by huey735** [comment]
I blended the dark and light blue of the original logo to limit the color scheme to only two colors.
![fedora](https://user-images.githubusercontent.com/44140017/59275399-26f14b80-8c54-11e9-8a2a-5d2fbfa51c8a.png)

**Comment by devinbileck** [comment]
Looks good to me!

**Comment by m52go** [comment]
Is the Fedora logo a different shade of green than the icons above it? It looks lighter.

@huey735 would you like to make a pull request? Otherwise feel free to post the icon files here and I can take care of it.

**Comment by huey735** [comment]
@m52go Thanks for the color comment. I fixed it and went ahead and made a pull request.

**Comment by m52go** [comment]
This was taken care of with #189. Closing as complete.
