### ISSUE TITLE
Download link to Source Code doesn't work

### ISSUE THREAD

**Issue by kopite77** [bisq-network/bisq-website#132]
On both the bisq.network homepage and the https://bisq.network/downloads/ page, the "Source Code" download links return a "Not Found" error. These are the links that return the error:
https://github.com/bisq-network/bisq/releases/download/archive/v0.9.4.tar.gz
https://github.com/bisq-network/bisq/releases/download/archive/v0.9.4.zip

Looks like the links should be as follows:
https://github.com/bisq-network/bisq/archive/v0.9.4.tar.gz
https://github.com/bisq-network/bisq/archive/v0.9.4.zip

**Comment by devinbileck** [comment]
Whoops, looks like my recent redirects have an issue. I will fix that.
Thanks for reporting this!
