### ISSUE TITLE
.deb package should be clearly labeled as amd64-specific

### ISSUE THREAD

**Issue by JeremyRand** [bisq-network/bisq-website#136]
I tried to download the `.deb` package linked from https://bisq.network/downloads/ , since it was labeled as "Debian/Ubuntu" and I'm running Debian.  Unfortunately, I then discovered upon trying to install it that the package is for `amd64` architecture only, which posed a problem since I'm running on `ppc64le` architecture.  Clearly labeling the download would have saved me some trouble.

**Comment by m52go** [comment]
@devinbileck can this simply be solved by putting `amd64` in the filename?

**Comment by devinbileck** [comment]
Yes, I think that is a good idea. Rather than simply 64bit in the filename, we could change it to amd64. Or I would suggest the more common term these days, x64.
Perhaps @ripcurlx can update the release scripts since he will be running them shortly? ;)

Additionally, perhaps the website should be updated to indicate this as well?

**Comment by ghost** [comment]
There is amd64 and arm64.
x64 could mean it's for both (which is not the case).

**Comment by ripcurlx** [comment]
As I'll create a release in the next couple of hours, let's move this change to the next release.

**Comment by devinbileck** [comment]
> There is amd64 and arm64.
> x64 could mean it's for both (which is not the case).

That is a valid point. Typically x64 refers specifically to x86-64, which is also known as the generic branded term amd64.

Unfortunately there is no consistency in the industry as to which term is used. From the x86-64 wikipedia page:
![image](https://user-images.githubusercontent.com/603793/57096702-bce79d00-6cca-11e9-98ea-63f4b2fca8ed.png)

**Comment by ghost** [comment]
Debian still uses the amd64 , arm64 terminology
https://www.debian.org/CD/http-ftp/

**Comment by m52go** [comment]
Closing as stalled/dropped. The fix needs to happen on the development side anyway, so please open a new issue in https://github.com/bisq-network/bisq to have it addressed.

**Comment by maresol-py** [comment]
Hello,

I decided to move to Linux OS after I had a problem using Windows 11.
I'm a newbee on Linux OS.
I use an WMware Fusion on macOS ARM64 to virtualize the Debian Linux.

But, when I tried to install Bisq on it, I receive the error below:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'bisq:amd64' instead of './Bisq-64bit-1.9.21.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bisq:amd64 : Depends: libc6:amd64 but it is not installable
              Depends: zlib1g:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

If it's compatilble to arm64 and amd64, why when I tried to install it selected "amd64" and stop the install process?

If it is compatible to both, why I couldn't install on arm64?

Can someone help me?

Thanks in advance.
