### ISSUE TITLE
Long sat values on trades (ie: .00000004) show up abbreviated. Is this by design?

### ISSUE THREAD

**Issue by nihirisuto** [bisq-network/bisq-website#139]
See screenshot. I think this is confusing personally. 
<img width="1136" alt="screen shot 2019-03-06 at 6 43 06 pm" src="https://user-images.githubusercontent.com/32186637/53928754-1a9b9800-4040-11e9-8613-d6ceb025d114.png">

**Comment by HarryMacfinned** [comment]
Are you sure it was .00000004 = 4x1e-8 at this time ?

**Comment by ghost** [comment]
You are right, it should be 4x1e-8. 
Or 5x1e-8 right now.

**Comment by m52go** [comment]
@chris-larsen thanks for pointing this out. It's not by design. Fix incoming.

**Comment by m52go** [comment]
Merged, closing. Let us know if you still see issues.
