### ISSUE TITLE
Add recent Teil 4 Barcelona interview to press page

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#14]
There are some past events/articles/interviews not added to the press page yet:

Interview:
- https://www.youtube.com/watch?v=lpm2tAQLEgc

**Comment by cbeams** [comment]
Closing as complete. Note however that the change is only visible on the staging site at http://bisq.beams.io/press/, as we have not yet gone live with the Jekyll-based site.
