### ISSUE TITLE
update market screen at https://bisq.network/

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-website#146]
The screen copy of the Bisq appli at https://bisq.network/ is quite old.
BTC/USD was at 9236.50 at the time (!)
Some newcomers may believe that the appli is not up-to-date.

**Comment by m52go** [comment]
I see your concern but I don't think it's something we need to worry about.

While the past couple of months have been pretty flat, BTC price is generally volatile, and I'm not sure we should commit to keeping that screenshot current (with respect to bitcoin price).

Another thing to keep in mind is that every new image we add to the repository forever enlarges the size of the whole repository, so we should try to only add new images when it's absolutely necessary.

Will keep the issue open through the week for comments from others.
