### ISSUE TITLE
Markets page price wrong

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#166]
The displayed altcoin price seems to be inverted.
<img width="2064" alt="Screen Shot 2019-04-16 at 17 43 57" src="https://user-images.githubusercontent.com/1449498/56248879-64c85e00-606f-11e9-8726-9eb384125e26.png">

**Comment by ManfredKarrer** [comment]
As I assume https://coinmarketcap.com/exchanges/bisq/ uses the same API it seems an issue on the webpage side not on the markets server.

**Comment by m52go** [comment]
Yes this has been an issue for a while, but when I investigated earlier, fix was not trivial so I put it off. Will look at this week.

**Comment by ManfredKarrer** [comment]
I think price is inverted atm. 1 / price is probably correct. If still not then it might be precision. Fiat has precision 4 and altcoins 8.

**Comment by m52go** [comment]
Closing as complete, as this issue was fixed with #171.
