### ISSUE TITLE
Make website translatable

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq-website#173]
We would like to start translating certain Bisq pages which may help greatly with growing our user base. We need main pages to be translatable to start our work.

**Comment by m52go** [comment]
Which parts of the website do we want to target first? How many languages? 

Is it possible to tackle translations one component at a time? Example: want to add Portuguese and Spanish. Is there a way to get both translations for the front page, and then get both translations for the Vision page, and so on?

**Comment by huey735** [comment]
We should start from the most superficial to the most technical. I think the Home page, Downloads, FAQ and Getting Started Documentation are the priority. Do you have stats on what pages get more visit? That'd be another criteria to go by.
We could go by the finished translations for the software on Transifex, which would give us Russian, German and Portuguese.

**Comment by arunasurya** [comment]
I think we need to have a call so that the writers, translators, ambassadors and anyone who is involved in growing the network can share their views. One of the contributors has already started translating some pages into Spanish, so we should include Spanish as well. Someone else suggested translating Getting Started Documentation, so maybe we can start with that and the Home Page, as @huey735 suggested? In any case, we will need input from @ripcurlx and others before we start any work.

Maybe we can have a call some time the second or third week of May?

**Comment by arunasurya** [comment]
I have spoken to @ripcurlx about this, and he suggested that we tackle the issue on several fronts:
- Design: @pedromvpg may need to be involved to make changes in the design to accommodate for the translations.
- Implementation: changes will need to be made in page format for certain languages, and we need to figure out how to connect them with Transifex.
- Content: we need to decide which pages we will start with. We will need to carefully look over the text and possibly simplify it to make translations easier. @m52go , we might need your help with this.
- Languages: ideally, we would like to have the site available in all the languages that are in the Bisq release. We might want to start with the following languages: Spanish, Portuguese, Russian, French and Chinese. Unlike the bisq-desktop project, each language translation can occur separately. In any case, we need to decide what market we want to target, etc.

I would be happy to coordinate this project. Let me know who wants to be involved, and we can start with this some time in May. We are planning to set up our first translator call the second week of May, so maybe we can combine the calls?

**Comment by MwithM** [comment]
Hello, I'm one of the Spanish translators.
I think that the documents that @huey735 has suggested are the main focus we should have.
Maybe there's very little need of translating most technical documents, because devs are usually English fluent speakers.
Knowing what users pay more attention when navigating Bisq page can be helpful to decide where should we begin with.

**Comment by ArnaudFR86** [comment]
Hello, I have just complete the first stage of the French Translation, I translated most of the terms but some are still in English yet, in particular those having a "path" for files nagivations/menu. and for others words, like "seed" and "peers", or taker and maker. Sometimes in French we use the English word, like we use "blockchain" and "peer to peer" or even "burn" like  in the sentence "faire un burn" and not " faire une brulure" ou brulage. The running version of Bisq alreday use Pair for peer and graine for seed, so I can change it in the pending translation version but you decide. I think a glossary/help included in Bisq could help users to get the meaning of some functions translate into their langage if we keep some English terms in the final translation. keep in touch.

**Comment by goo-technology** [comment]
Hello, i have main page, vision and dao sections already translated to spanish and this week i will finish the faq.

I have it all in a Google docs folder if needed to share with other spanish translators

Also i made two small slideshows with the whole page info in spanish if somebody need it

**Comment by arunasurya** [comment]
@goo-technology , great! We can talk about it on the call, and see how we can integrate it into Transifex!

By the way, our first call is scheduled on [May 7th, at 13 CET](https://github.com/bisq-network/growth/issues/129). It would be great if someone from the developer team joins the call as well.

**Comment by criptonauta** [comment]
Hi

I have the same as @goo-technology but in Brazilian Portuguese (Home, Vision, working on FAQ page)

The most important non technical pages are Home, Vision and FAQ. The remaining pages are somewhat easy to be translated, considering they have less text and more images.

Getting Started is also important, but it is a different section (documentation) in a wiki like structure. IMO, the wiki should be dealt separately, after client and webpage are completed.

**Comment by arunasurya** [comment]
The recording of the translator call is now available on [YouTube](https://www.youtube.com/watch?v=nAE0EdojliQ&list=PLFH5SztL5cYPPMIBM22SbqrJ01AXTeVY_). Here is a quick summary of the call, regarding translating the Bisq site.

## Bisq pages we are going to translate:
- Home page
- Vision 
- Bisq DAO 
- Statistics 
- FAQ 
- Markets
- Getting Started with Bisq (documentation) 
- Downloads 

## Languages
Ideally, all current languages in the client (nine), but we will start with the following: Spanish, Portuguese, Russian, French, Chinese (Mandarin).

## Next steps:
- @huey735 is testing ways of transferring site info to Transifex. Perhaps we can add info on this in [this spreadsheet](https://docs.google.com/spreadsheets/d/1XsqW25NagRZEo8fPb4Sj-8Ov6WFX9Os94IS9UPiE_Ak/edit#gid=0)?
- As soon as we have the docs in Transifex, we can start with the translation.
- We will need help from @pedromvpg for any changes in the design.

## Suggestions
- @criptonauta shared a translator checklist - any ideas on what items we should include as part of this project?: https://cdn-txweb.pressidium.com/wp-content/uploads/2016/05/Website-Translation-Checklist-Transifex.pdf

**Comment by MwithM** [comment]
@goo-technology Great news. Could you please share the doc?

I'm looking forward to see these website pages ready to be translated on transifex.

**Comment by huey735** [comment]
I've uploaded some files to Transifex so we can start testing the process of translation of the website - https://www.transifex.com/bisq/bisq-website/content/.

For those of you who have started to translate the homepage_content.html file, please copy your translations to the strings.yml resource. That file contains all strings in the homepage_content.html file and more, making homepage_content.html redundant.

The goal is to try to go through the process of translation of the website so we can see what works and what doesn't. The clone demo of the site lives at https://github.com/huey735/huey735.github.io and can be seen at huey735.github.io. This is where I'll be uploading the translations so we can test it out.

Bellow you can read more about the process
https://docs.google.com/document/d/1NPRqwO6-_hjp3jUJsXpCrDAo7LH8_PaCu72180KrsRk/edit?usp=sharing


@pedromvpg  we'll need your help for the translations of some images on the website.

**Comment by huey735** [comment]
I'm thinking of adding the "Community" page to this phase of translation. It has very little content to translate and it completes the in-site pages.

**Comment by arunasurya** [comment]
@huey735 , great idea! Perhaps we can even add more info for specific languages such as Portuguese translations of the Bisq DAO in brief series or ambassador activities in certain Spanish-speaking countries?

**Comment by arunasurya** [comment]
Here is a brief summary of the project, based on the second translator call:
- @huey735 is the owner of the part of the project that deals with transferring files to Transifex and translations to the Bisq website. This is a manual process.
- We now have the `bisq-website` project in Transifex where some of the files are available, and have already been translated into several core languages. 
- The pages can be translated into all the current core languages (Portuguese (Brazil & Portugal)), Spanish, French, Russian, German, Chinese, Persian, Thai and Vietnamese).
- The files are grouped into separate docs based on their type (html, yml, md).
- We will add the Community page to the list of the translatable pages.
- The url is not going to be translated, but the target language will be mentioned in the link.
- The translations will be regularly updated by @huey735 (either monthly or along with each new release). In case there is a very important change on the website (e.g., changed in the trade protocol), that will be announced, translated and updated as soon as possible.
- Some strings are marked as `no translate` in Transifex - they should left as they are.
- The text in the images on Bisq DAO page will be translated on Transifex and @huey735 will update the images in each language manually.
- @m52go will look into transferring the Started documentation (ascii doc) to Transifex.

@huey735, please correct me if I am wrong on any of these points. Thank you for all the great work!

**Comment by m52go** [comment]
This was completed with #190 (primarily), with small bugs fixed with #197 and #201. 

Since then Chinese, German, and Spanish have been added. Big thanks to @huey735!
