### ISSUE TITLE
Fix dropdown styling quirk on tor browser

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-website#175]
The download dropdown styling is buggy on the Tor browser:

![Screenshot from 2019-05-02 08-48-15](https://user-images.githubusercontent.com/735155/57076208-134ae080-6cb7-11e9-828c-979cd74d6442.png)

**Comment by ghost** [comment]
Hello @m52go 
I just verified with pure Firefox on Debian, and I have the exact same picture.
So I would say that it seems related to Firefox.

**Comment by m52go** [comment]
Pure Firefox on Ubuntu did not show the problem for me...strange.

**Comment by m52go** [comment]
@HarryMacfinned @arunasurya should be fixed now. Please let me know if it's not. I can't test on Debian with Firefox but the problem is gone for me in the Tor browser on Ubuntu where I previously reproduced it.

**Comment by arunasurya** [comment]
Looks good for me, @m52go :). Thanks!

**Comment by ghost** [comment]
Looks also good for me. Thanks.
