### ISSUE TITLE
Blog Topic: MimbleWimble Coins and Bisq

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq-website#178]
BSQ requested: 100 

Whenever we can test and relist Grin, we can write a how-to blog post on trading mimblewimble coins on Bisq using the updated [wallet713](https://github.com/vault713/wallet713/pull/88) (includes payment verification feature) and [Grinbox](https://github.com/vault713/grinbox).

I was thinking this piece can be written in anticipation of a Grin-fork airdrop to Bitcoin holders called [MWC](https://www.mwc.mw/) occurring on July 19th 2019.

This can be a good chance for new user adoption and some volume.

For maximized growth we can translate the tutorial into other languages.

**Comment by m52go** [comment]
Although blog posts are elements of the website, with the new [growth infrastructure](https://bisq.wiki/Growth_Team#Infrastructure), it makes more sense to manage blog post _ideas_ on the [growth kanban board](https://grow.bisq.cc/b/jPBBopYuLdGYdDpvF/markets) so it's easier to relate them to current priorities.

Of course, blog posts will continue to be submitted as PRs and reviewed here as usual.
