### ISSUE TITLE
Blog topic: What is a Bisq Liquidity Week?

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq-website#179]
BSQ requested: 50
This can be a small writeup describing what a Bisq liquidity week looks like with a call-to-action to participate somewhere in the blog post.

The body can consist of something along the lines of:

What is a Bisq liquidity week?
Past liquidity week successes. 
Why we have liquidity weeks.

**Comment by m52go** [comment]
Although blog posts are elements of the website, with the new [growth infrastructure](https://bisq.wiki/Growth_Team#Infrastructure), it makes more sense to manage blog post _ideas_ on the [growth kanban board](https://grow.bisq.cc/b/jPBBopYuLdGYdDpvF/markets) so it's easier to relate them to current priorities.

Of course, blog posts will continue to be submitted as PRs and reviewed here as usual.
