### ISSUE TITLE
Blog Topic: How Bisq can help Venezuelans buy Bitcoin

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq-website#180]
BSQ requested: 50 

Venezuelan volume on LocalBitcoins is [quite large and growing](https://coin.dance/volume/localbitcoins/VES)

This piece can be a small writeup about how beneficial Bisq could be to Venezuelans suffering from hyperinflation and privacy concerns. 

Some headers can be:

LocalBitcoin Volume in Venezuela is Growing Quickly
Problems with KYC on LocalBitcoins
Bisq Offers More Privacy than LocalBitcoins
Why Bitcoin is Gaining Adoption in Venezuela

**Comment by ghost** [comment]
Nice idea. Thanks for that.

**Comment by Mycelial1** [comment]
I have a rough draft created here: https://docs.google.com/document/d/1ZYyIfrYrKolTWAMgyf_UcH5yfXTSYwE9GWzBsUu2sOM/edit?usp=sharing

**Comment by m52go** [comment]
@Mycelial1 is there a chance you could make that draft public, so people can review it without having to request access?

**Comment by Mycelial1** [comment]
@m52go  Yes. Try now.

**Comment by m52go** [comment]
@Mycelial1 pretty good I think. Couple of comments...how should I provide? I can't comment on the doc.

**Comment by Mycelial1** [comment]
@m52go Next blog post, I will make a pull request like Manfred did for his "Let the DAO work" post.  You can try to comment the doc now.

**Comment by m52go** [comment]
Although blog posts are elements of the website, with the new [growth infrastructure](https://bisq.wiki/Growth_Team#Infrastructure), it makes more sense to manage blog post _ideas_ on the [growth kanban board](https://grow.bisq.cc/b/jPBBopYuLdGYdDpvF/markets) so it's easier to relate them to current priorities.

Of course, blog posts will continue to be submitted as PRs and reviewed here as usual.
