### ISSUE TITLE
Blog Topic: What´s Bitcoin source of value

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq-website#182]
Hi all,

I suggest the following final draft for a Bisq blog post:

https://docs.google.com/document/d/1G5G_6JgaZraNURyjVYPE1XckfzIUZ_DB_A8eaIzn4Io/edit?usp=sharing

It is only related to Bisq in the sense it is related to Bitcoin, but not specific of Bisq at all.  I just thought to offer publishing on Bisq instead of my personal blog, but I am totally ok if you feel it should not be published here.

**Comment by Mycelial1** [comment]
Thanks. Will take a look and give feedback when I have a second. If you haven't already, you can join the slack channel (bisq.slack.com) and join the #blogposts channel to stay in touch.

**Comment by ManfredKarrer** [comment]
Great article!

**Comment by Mycelial1** [comment]
@mpolavieja I've made some edits and suggestions if you would like to review them.

**Comment by mpolavieja** [comment]
Thank you very much.  I have accepted all suggestions except one which I am not sure.  If you still think it stands I´ll accept it too.   I think I have to work a bit the conclusion and then it could be ready for publishing.  I expect to do that tomorrow.

**Comment by m52go** [comment]
Closing as complete, as this post was merged with https://github.com/bisq-network/bisq-website/pull/188.
