### ISSUE TITLE
[Proposal] Get rid of google analytics

### ISSUE THREAD

**Issue by erciccione** [bisq-network/bisq-website#191]
I think Google Analytics could be replaced with another more privacy-friendly service. For getmonero.org we use [Matomo](https://matomo.org/), which is self-hosted and open source. I think the bisq users would appreciate the switch :)

**Comment by wiz** [comment]
Yes, we should absolutely dump Google. I currently run Piwik / Matomo for some Bitcoin projects like bitcoin-only.com and it works very well as a self-hosted solution. I would be happy to run a Matomo instance for Bisq as well.

**Comment by erciccione** [comment]
Nice. Thank you :)

**Comment by wiz** [comment]
Yeah also on the Matomo side I have symlinked the access log to /dev/null and we will obfuscate visitor IP addresses so for example 1.2.3.X gets logged instead of 1.2.3.4

**Comment by wiz** [comment]
<img width="417" alt="Screen Shot 2019-08-23 at 1 10 16" src="https://user-images.githubusercontent.com/232186/63531128-cd09dd80-c542-11e9-9fe2-93b0059c6f84.png">
