### ISSUE TITLE
The website is using the wrong images in the pt-PT DAO page

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq-website#196]
For some reason that is beyond my understanding of Jekyll, the website served by Github is using the wrong images.

There is:
~/images/DAO/
- dao_benefits.svg
- dao_how.svg
- dao_intro.svg
- dao_what.svg
- dao_why.svg
and
~/pt-PT/images/DAO/
- dao_benefits.svg
- dao_how.svg
- dao_intro.svg
- dao_what.svg
- dao_why.svg

These folders contain the images rendered in bisq.network/dao and bisq.network/pt-pt/dao. I decided not to change the names of the .svg files because they're in different folders and that way we don't have to change any Liquid tags around the website.

These files are being requested by
pt-PT file ~/_data/dao_content_tr.yml which in in turn is being requested by ~/pt-PT/dao.html

If you clone the repository and run it locally, Jekyll uses the correct images for the pt-PT version of the DAO page.

@erciccione @m52go @ripcurlx

**Comment by huey735** [comment]
I have a copy of the website running on huey735.github.io where the only difference I can see is
url: "https://huey735.github.io"
On ~/_config.yml

And it renders the urls as pt-PT, as it should, and it fetches the correct images.

**Comment by m52go** [comment]
Fixed with #201.
