### ISSUE TITLE
[Feature] Torrent Downloads

### ISSUE THREAD

**Issue by ghbjklhv1** [bisq-network/bisq-website#224]
**Feature**: Support BitTorrent for file downloads

- [x] Anonymous Download
Related: https://xd-torrent.github.io/
- [x] Free/Libre Clients ([exist](https://directory.fsf.org/wiki?search=BitTorrent))
- [x] File Verification
https://stackoverflow.com/questions/35549004/does-bittorrent-verify-files-integrity

You can also verify that everybody got the same file, as long as the .torrent files are all the same.

**Comment by m52go** [comment]
@ghbjklhv1 I think it's a good idea, but is there an automated way to do this when binaries are uploaded to GitHub at the time of a new release?

If not, it might be best to leave this to the community. I don't think there would be an issue with providing magnet links or torrent file links or whatever is needed to make it work on the Downloads page, if someone one like to do provide such links, but I would be hesitant to make this a responsibility of the Bisq project maintainers. 

If I understand the process correctly, it wouldn't be a whole lot of work even if it weren't automated, but it's just 1 more thing that would need to be done for every new release, and the benefit is not clear to me (feel free to clarify; maybe I'm missing something).

**Comment by erciccione** [comment]
Agree with @m52go here and i want to add that Torrents are cool but require centralization (even if their authenticity can be verified, somebody has to host the torrent itself) and i don't see a clear benefit in in adding them unless bisq's servers are overflawed with download requests, and i think that's not the case.

**Comment by m52go** [comment]
Closing this -- the idea is good but it's not a high enough priority for us to devote resources to.
