### ISSUE TITLE
Change localization process

### ISSUE THREAD

**Issue by erciccione** [bisq-network/bisq-website#244]
This is something we briefly discussed in the past days. The way the website is translated now is a beginning, but not optimal. Some translations are in html files, other in yml and some sections need to be updated for each language. That makes working on translations hard and unmaintainable in the mid-long term.

As i suggested in past i think we should implement a better workflow. I think using the [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin) to manage the localization of the webste is the way to go.

SInce this approach received some positive feedback in the past I already started to work on this. It will take some time because requires a complete change of the structure of the repo and of most of the files, but after, the maintainance of the repo will be easier and the structure will be consistent for all languages.

Feel free to assign this issue to me

**Comment by wiz** [comment]
Does this plugin support country-specific locales?

**Comment by m52go** [comment]
@erciccione this could be very good, I think, as long as:
1. you think the effort is worth it...it seems like translations are a bit of a mess to maintain regardless, and changing the localization process probably only makes sense if it's significantly better than what we have now.
2. this plugin can be made to accept locales, as we discussed in #243. I know you're not a fan of that direction, but that's currently the way we'd like to go.

**Comment by erciccione** [comment]
The plugin doesn't care. It only changes the structure, we can use any language/locale we want. To clarify: My intention is not to revert or ignore the consensus reached in #243. A collective decision is law in an open source project, even if i was against it.

> you think the effort is worth it...it seems like translations are a bit of a mess to maintain regardless

If there is an interplanetary truth, is that translations are a mess to maintain :), but as i briefly explained, i think this plugin is really necessary. The present way is unmaintanable in the long run and touches too many files. It will only only get worse with every new language. This new way of doing things will make everything much easier for both maintainers and contributors.

**Comment by m52go** [comment]
Great, I figured that, but just wanted to make sure. Assigned this issue to you :)

**Comment by erciccione** [comment]
I'm not interested in working on this anymore. See https://github.com/bisq-network/bisq-website/pull/260#issuecomment-539960325.

**Comment by erciccione** [comment]
On a second thought, i think it's better to reopen this issue. This repo is still in a very bad shape and if new languages are added with the current system, they will only make the repository heavier and more messed up than it already is. A refactor is very needed and somebody else could be willing to pick up this task.
