### ISSUE TITLE
Blog topic: code is not law

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-website#251]
Bisq is not a protocol like Bitcoin or TCP/IP, but a service run by people for people, using software built by people. The software has protections in place to avoid extreme scenarios, but there will be bugs and attackers, and ultimately the code is more of an expression of intention than it is a final incorruptible almighty law. 

While we hope nothing will be catastrophic enough to require it, Bisq has established that hard forks are an option to deal with extreme scenarios.

**Comment by ghost** [comment]
Law is, as its roots, nothing else than an expression of intention.
And it's not rare to have results at 180° of intentions.
imo code is law, ie with the same kind of flaws.

**Comment by m52go** [comment]
@HarryMacfinned I guess I meant "law" in a more simplistic way, more like a figure of speech, wherein "law" is thought to be an immutable construct with no ambiguity. 

Practically, you're right, that's not at all the case. In Szabo's terms, law is very much "wet code".

I will note this in the post.

**Comment by m52go** [comment]
Although blog posts are elements of the website, with the new [growth infrastructure](https://bisq.wiki/Growth_Team#Infrastructure), it makes more sense to manage blog post _ideas_ on the [growth kanban board](https://grow.bisq.cc/b/jPBBopYuLdGYdDpvF/markets) so it's easier to relate them to current priorities.

Of course, blog posts will continue to be submitted as PRs and reviewed here as usual.
