### ISSUE TITLE
`/contribute` still uses old bitsquare logo

### ISSUE THREAD

**Issue by eljobe** [bisq-network/bisq-website#26]
Almost all of the banner images on the website use the bisq logo, but https://bisq.network/contribute/ is still using the bitsquare logo.

Compare the Community banner image:
![community](https://github.com/bisq-network/website/blob/master/images/community.png?raw=true)

With the Contribute banner image:
![contribute](https://github.com/bisq-network/website/blob/master/images/contribute.png?raw=true)

Happy to do the image editing, but I imagine there are some underlying resources (i.e. Photoshop,  Affinity Photo, SVG) files which aren't publically available that would make the task much easier for someone already in possession of those files.

Consider making those resources public as well?

**Comment by cbeams** [comment]
Good catch, thanks Pepper! I've actually been aware of this, but haven't changed it as the general plan is to radically simplify the website in the near future, possibly doing away with these banners (and indeed possibly with this page).

With that said, it would be cool to have it changed in the meantime. I do not personally have the source files for these images, but perhaps @ManfredKarrer does.

Manfred, can you attach these resources if you have them?

**Comment by ManfredKarrer** [comment]
Thanks @eljobe for catching that.
The header file was created but seems it was not uploaded....
Here it is:
![contribute](https://user-images.githubusercontent.com/1449498/30386458-7ab502e6-986f-11e7-8613-6ae157c5d06e.png)

**Comment by cbeams** [comment]
Closing as fixed. Thanks again @eljobe!

![image](https://user-images.githubusercontent.com/301810/30512137-5a822a50-9ae8-11e7-9b68-5a67d5199339.png)
