### ISSUE TITLE
Signing key is missing

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#29]
Signing key is missing in https://bisq.network/pubkey/F379A1C6.asc (used for in-app downloader)

Key is at:
https://github.com/bisq-network/exchange/releases/download/v0.5.3/F379A1C6.asc

**Comment by cbeams** [comment]
Hm. The key is present for me:

```
$ http head https://bisq.network/pubkey/F379A1C6.asc
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 43
Cache-Control: public, max-age=0, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 7482
```

See commit 465ed7e576203954fb795cbbda1fe33eb28e8d72 / bisq-network/exchange#900 for details.

**Comment by cbeams** [comment]
Closing as invalid. Confirmed with @ManfredKarrer via Slack that the key is in fact correct. The in-app downloader is referencing it via the bisq.io domain, but redirects are in place. Appears all is well.
