### ISSUE TITLE
Remove negative left margin from headers in homepage

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq-website#311]
Its time to remove the negative margin and standardize the website layout.
It was a stylistic move that had no meaning and did not improve the experience.

A lot of people got confused with it.

```
.row-block h2 {
    /*margin: 2em -55px;*/
    margin: 2em 0px;
} 
```

<img width="1726" alt="Screen Shot 2019-12-05 at 8 29 04 PM" src="https://user-images.githubusercontent.com/807505/70287824-54035e80-179e-11ea-8eeb-3f7ae1806283.png">
<img width="1726" alt="Screen Shot 2019-12-05 at 8 29 39 PM" src="https://user-images.githubusercontent.com/807505/70287825-54035e80-179e-11ea-9edf-521e3cdf1b8c.png">
<img width="1726" alt="Screen Shot 2019-12-05 at 8 29 48 PM" src="https://user-images.githubusercontent.com/807505/70287827-54035e80-179e-11ea-8050-4357f8a428a7.png">

**Comment by m52go** [comment]
Done with #314.
