### ISSUE TITLE
Add openSUSE to the rpm package download label

### ISSUE THREAD

**Issue by m-rey** [bisq-network/bisq-website#326]
At the moment, the rpm package is [listed as the download option](https://bisq.network/downloads/)  for Red Hat/Fedora. This can also be seen on download drop-down menu of the main page.
I would propose to add openSUSE to that entry, as it also uses rpm packages and is a [popular distribution](https://distrowatch.com/table.php?distribution=opensuse).

**Comment by m52go** [comment]
Appreciate the thought, but if we started to list the full array of distros that can install RPMs and DEBs...we'd run out of space. Along with Red Hat and Fedora are SUSE OSes and CentOS. And there are a ton of popular distros that are based on Debian.

I think Linux users are smart enough to know when they need a .deb or .rpm or something else, so this isn't strictly needed.
