### ISSUE TITLE
The markets page is publishing duplicates of trades

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq-website#338]
### Description

The bisq.network/markets page is publishing the same trade twice seemingly for all markets. This issue seems to have started on February 7th 2020. From looking at the big markets, the first instance of the issue seems to be at 15h33m10s for the EUR market.

### Screenshots
![Screenshot from 2020-02-09 15-43-31](https://user-images.githubusercontent.com/44140017/74105245-04e9f900-4b54-11ea-8589-e3bd05602060.png)
![Screenshot from 2020-02-09 15-43-51](https://user-images.githubusercontent.com/44140017/74105246-05828f80-4b54-11ea-9b53-91f4a1d1312b.png)
![Screenshot from 2020-02-09 15-58-17](https://user-images.githubusercontent.com/44140017/74105393-34e5cc00-4b55-11ea-81c3-a6a296538643.png)

@wiz @ripcurlx I think I caught you discussing it, so I thought I'd mention you both here.

**Comment by wiz** [comment]
Thanks for reporting, but yeah, we know - unfortunately v1.2.6 release branch has some major issues which we are working on, yesterday I had upgraded the node which serves data to the Markets API but reverting it to v1.2.5 now

**Comment by wiz** [comment]
BTW in the future you can report market issues to bisq-markets repo

**Comment by wiz** [comment]
@huey735 can you confirm this issue is resolved and if so close the issue? thanks

**Comment by huey735** [comment]
It does look like it's fixed. In the future I'll make sure to post it on the correct repository.

**Comment by ripcurlx** [comment]
There are still around 400 trade statistic duplicates in the data store that were added by trading with our current master (which have the v1.2.6) changes in there. As soon as https://github.com/bisq-network/bisq/pull/3958 is merged and deployed these duplications should be remove as well. Including the privacy test trades by @wiz :wink:
