### ISSUE TITLE
List Matrix channel on Community page

### ISSUE THREAD

**Issue by JeremyRand** [bisq-network/bisq-website#346]
Bisq's Freenode channel (listed on the Community page) states in the channel topic that it is synced with Matrix.  However, neither the Freenode channel topic nor the Community page state which Matrix channel that is.  I can find two different Matrix channels (`#bisq:matrix.org` and `#bisq.network:matrix.org`; I'm guessing the former is the correct one but I'm not certain), and it's conceivable that phishers will set up additional Matrix channels in efforts to scam users.  It would be useful for the Community page to list the correct Matrix channel so that Matrix users know which channel to join.

**Comment by RiccardoMasutti** [comment]
Correct one is https://webchat.freenode.net/?channels=bisq

**Comment by JeremyRand** [comment]
> Correct one is https://webchat.freenode.net/?channels=bisq

@RiccardoMasutti ...that's an IRC channel.

**Comment by m52go** [comment]
@JeremyRand thanks for pointing this out. I also think the room most people use is `#bisq:matrix.org`.

However, it's not clear to me how to handle the situation regarding Matrix and IRC...activity is infrequent, and I'm not sure any regular contributors hang out in either place. Further, I'm not sure who moderates those channels, and I also haven't been successful in contacting the contributor who originally set up the matterbridge server that makes the bridging possible. 

So frankly I'm not sure it makes sense to list either on the website.

At this point, I'm leaning toward removing IRC from the website too and leaving Matrix and IRC in the community's hands to manage.

What do you think? I think I've seen you post from IRC a few times...is my assessment off? I don't hang out much there myself.

**Comment by JeremyRand** [comment]
@m52go I tend to prefer methods of communication that have open-source implementations and which are friendly to Tor users.  So, from that perspective, OFTC IRC would be ideal for me; Matrix is 2nd-best, Freenode IRC is 3rd place, and things like Slack and Keybase (which I think are the two that Bisq devs tend to use?) are a distant last.

I don't have any magic solutions for you though; it's certainly a problem if you don't have any reliable contact info for the moderators of the channels or the operators of the bridges.  Given that Bisq tends to be a community project, there's not much that can be done if no one steps up to do that work.  (And I definitely don't have enough free time to volunteer for it; I'm already busy enough managing Namecoin infrastructure.)

It is kind of disappointing that a project strongly focused on decentralization and open-source software such as Bisq is using heavily centralized, closed-source communication mediums for most of its development.  I'd definitely like to see that improve (as I'm sure you would too), but as with all things, wishing for an improvement is a lot easier than putting in the time to make it happen.

Speaking for my personal preferences, I would be highly unlikely to join Slack or Keybase in order to talk to the Bisq devs.  If no IRC or Matrix option is available, then I'll probably resort to other mediums like the forum, GitHub, or email in order to discuss things with the Bisq devs.  (Though I have major reservations about all 3 of those mediums too.)  I realize though that my involvement with Bisq is rather minor compared to a lot of contributors, so my preferences may or may not weigh heavily on your decisions.

**Comment by m52go** [comment]
@JeremyRand highly appreciate your thoughtful answer, and I agree. We've been treading a fine line between principle and practicality (as it applies to everyday users who just want help with a trade without having to figure out what IRC is)...and I'm not sure we've figured out the right balance yet.

For what it's worth, Slack is now decommissioned and Keybase is what we primarily use.

As for how to handle the matter at hand—I've been thinking of ways to bridge gaps among all our communication mediums (there are too many) without disenfranchising anyone. There's nothing stopping us from simply creating another matterbridge server for 2-way mirroring of IRC and Matrix into Keybase so those channels can become lively, well-attended, and worth it for users to join.

To that end, once I run this by others and determine how to make this work, I'll make a PR to add the Matrix channel to the website. We're in the midst of a month-long March liquidity campaign, so I can't promise it'll be done immediately, but can make it a priority for April.

**Comment by m52go** [comment]
Completed with #395.
