### ISSUE TITLE
Bisq.network On-Site Search Engine Optimization

### ISSUE THREAD

**Issue by RiccardoMasutti** [bisq-network/bisq-website#351]
I propose to continue Search Engine Optimization work as defined in [Bisq Growth Guidelines](https://gist.github.com/m52go/4e0e5c5f8fef4d71e22ee4eaa742d141). Specifically, for Cycle 10 and 11, we need to focus on liquidity. For this reason I propose to include it in the budget for Cycle 12.

There are still several errors within the pages like image missing alts/not optimized, H1 H2 H3... missing, meta tags missing. Furthermore, in the future, a keyword research and optimization of the site pages would be required. This will take some time so I would say to postpone it to the next cycles (13? 14?)

With regard to this proposal, the works that I would carry out are the following:
- Missing image `alt` attributes
- Missing links `title` attribute (eg. #348, #349, #350 ready to merge)
- Missing `meta` attribute (eg. #347 ready to merge)
- Missing titles

In addition, it would be smart to automatically minify the code, it would save a good 15% of loading time.

Estimated delivery date: 31 March
Cost: 420 BSQ

**Comment by m52go** [comment]
Rejected, per https://github.com/bisq-network/compensation/issues/463#issuecomment-597069076.
