### ISSUE TITLE
Add search to website

### ISSUE THREAD

**Issue by stevavoliajvar** [bisq-network/bisq-website#369]
Bisq website would be much better with a search.

Since this site is static there are ways to implement search with using [minisearchjs](https://github.com/lucaong/minisearch). I have experience in implementing it, implemented [here](https://flakhobby.com), and would like to make it work for bisq website if bisq community is ok with it.

Roughly technical process would consist in building an index file, search form and appropriate javascript code.

**Comment by m52go** [comment]
@stevavoliajvar hey thanks for the offer. 

We're very close to rolling out a wiki, which will become the go-to resource for information about Bisq. That will probably lead to the website being simplified soon afterward, so I don't know if adding search would be worth the effort.

Is there anything in particular that you important but hard to find? It might be helpful to know as we structure the wiki and/or restructure the website.

**Comment by stevavoliajvar** [comment]
Fair point. 

Then I'd suggest, since wiki has search, to make search input field on website routes to wiki search via `action` attribute in HTML.

**Comment by m52go** [comment]
Now that wiki is in more active use, maybe we could do this. @stevavoliajvar would you be interested? 

Main thing on my mind is figuring out a place to put the search box. Site is already so crowded...

I imagine it opening a new window with wiki search results.

**Comment by stevavoliajvar** [comment]
@m52go i see this just now, I would like to do this. 

The place can be a simple looking glass icon before change theme icon that would open search prompt, either full screen or just spread out input field. Then that form is connected with bisq.wiki search and redirects user to there.

**Comment by m52go** [comment]
That sounds good. I think a spread-out input field would be better. Should results open in a new tab, since wiki is a different site?

**Comment by stevavoliajvar** [comment]
@m52go I think it should because it takes user to a new webstite, so previous one still gets opened. But if people don't like it then we can easily revert back to the same tab. 

I will report within a week from now regarding this issue.

**Comment by stevavoliajvar** [comment]
@m52go here is the [preview](https://deploy-preview-411--bisq-website.netlify.app/) and a [pull request](https://github.com/bisq-network/bisq-website/pull/411)

I decided to just put a simple search field in the end, because other solution with full screen search would require JavaScript which is not necessary and overkill in my opinion.

**Comment by m52go** [comment]
Done with #418.
