### ISSUE TITLE
Revisions to Getting Started page visual styles

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq-website#372]
Proposing a couple of changes to the layout and copy on the getting Started page to make it more inviting and legible.

![image](https://user-images.githubusercontent.com/807505/85211544-49627e00-b318-11ea-9142-4cfdeffba66f.png)

- Revise header
- Make more actionable copy in to bullet lists
- Add max widths so lines don't get too long
- Increase negative space
- Move selection tabs to the bottom of the videos
- Revise final notes layout

<img width="2428" alt="Screen Shot 2020-06-20 at 4 26 43 PM" src="https://user-images.githubusercontent.com/807505/85211610-bfff7b80-b318-11ea-9e04-43ecc589fdc5.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 30 14 PM" src="https://user-images.githubusercontent.com/807505/85211611-c2fa6c00-b318-11ea-810b-93482835fd89.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 34 55 PM" src="https://user-images.githubusercontent.com/807505/85211612-c4c42f80-b318-11ea-9aa7-c44b7277ac8d.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 40 29 PM" src="https://user-images.githubusercontent.com/807505/85211613-c5f55c80-b318-11ea-840a-56cf7b603d42.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 42 43 PM" src="https://user-images.githubusercontent.com/807505/85211614-c7268980-b318-11ea-8515-cddf113835d9.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 46 03 PM" src="https://user-images.githubusercontent.com/807505/85211616-c857b680-b318-11ea-8696-d0ca6fef03c4.png">
<img width="2428" alt="Screen Shot 2020-06-20 at 4 59 31 PM" src="https://user-images.githubusercontent.com/807505/85211617-c988e380-b318-11ea-8b8a-9ccd4dd634d3.png">

**Comment by m52go** [comment]
Closing as complete now that #380 is merged.
