### ISSUE TITLE
Invalid link to slack workspace

### ISSUE THREAD

**Issue by blabno** [bisq-network/bisq-website#39]
- When I enter https://bisq.network/community/
- And I click `Bisq Slack workspace` link
- Then I am redirected to `https://bisq.slack.com/join/shared_invite/enQtMjg5MjE4OTQ2MTE5LWFkMjE5M2E5OTYwM2QyM2JmMzUxZmZlNmU0NTM5ZDIwOTBhMzFjOGY5NzYyODc5ZGVjMjM1ZTVkYjFlNzdlZjg`
- And I see `This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available.`

**Comment by cbeams** [comment]
Closed with commit 9b802a4. Thanks, @blabno!
