### ISSUE TITLE
Trade History should display whether trade was a sell or buy

### ISSUE THREAD

**Issue by rating89us** [bisq-network/bisq-website#417]
In Markets pages (for instance, https://bisq.network/markets/?currency=xmr_btc), _Trade History (Last 100 trades)_ section should display a trade in red (if it was a sell) or green (if it was a buy). 

For example, like this trade history from kraken exchange: 

![image](https://user-images.githubusercontent.com/45968869/103574364-0f318600-4ed0-11eb-8ffd-6f0ee7c4297c.png)

**Comment by m52go** [comment]
This is no longer possible, unfortunately. Trade direction used to be shown, but [had to be removed](https://github.com/bisq-network/bisq-website/commit/b09c98148204efd448f41b9b72781c7e55bf7163) when trade direction was removed from Bisq's trade statistics.
