### ISSUE TITLE
wip: Accessibility issues

### ISSUE THREAD

**Issue by kiddhustle** [bisq-network/bisq-website#422]
I have noticed accessibility issues whilst reviewing the site.

Running a quick test on the homepage (using [aXe a11y tools](https://www.deque.com/axe/)) the 26 issues are found. They are summarised as follows:

Critical:    3
Serious:    9
Moderate:    8
Minor:    3
Review:    3

These issues can have negative implications for users reliant are screen readers/assistive technologies. Fixing them will probably have SEO benefits also.
How highly does the Bisq value accessibility?

**Comment by Conza88** [comment]
_Fixing them will probably have SEO benefits also._

Definitely need some of that imo.

**Comment by m52go** [comment]
@kiddhustle can you give more details on what exactly these issues are?

**Comment by kiddhustle** [comment]
@m52go I will try to post more details tomorrow when I have access to my laptop 👌🏾

**Comment by kiddhustle** [comment]
@m52go accessibility issues are as follows (for the home page only):

* Elements must have sufficient color contrast - 2
* Frames must have title attribute - 1
* Images must have alternate text - 2
* Links must have discernible text - 1
* `<ul>` and `<ol>` must only directly contain `<li>`, `<script>` or `<template>` elements - 1
* `<li>` elements must be contained in a `<ul>` or `<ol>` - 5
* Links with the same name have a similar purpose - 1
* `<video>` elements must have captions - 1
* Heading levels should only increase by one - 2
* Alternative text of images should not be repeated as text - 3
* Zooming and scaling must not be disabled - 1
* All page content must be contained by landmarks - 6

<img width="1298" alt="Screen Shot 2021-02-02 at 09 29 38" src="https://user-images.githubusercontent.com/858994/106579932-34e69500-6539-11eb-9fd0-58a6645a9e37.png">

**Comment by m52go** [comment]
I'm not sure it makes sense to spend time on most of these things...thanks for offering though.

**Comment by kiddhustle** [comment]
OK sure no problem
