### ISSUE TITLE
Typo in FAQ under "Does Bisq support ‘XYZ’ payments?"

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq-website#45]
National bank transfer is supported in every country (**_expect_** the US - but there is Zelle and others).

Should be **_except_**.

**Comment by cbeams** [comment]
Closing as complete. I cherry-picked the commit from your repository @ghubstan. In the future, please:

- submit changes as a pull request
- update your Git author metadata to use your first and last name. (it currently reads `author` right now:
```
commit bfae745a8d785fe99a331db8b772ef058dc2a39a
Author: author <sburnitt@gmail.com>
Date:   Wed Feb 28 14:43:26 2018 -0300

    Fix typo

    Issue #45
```

**Comment by ghubstan** [comment]
Sorry for the error.  Will you clarify what I did wrong, RE: "submit changes as a pull request"?
I created Issue #45, and then  PR #46.  Where did I go wrong?
Thanks.

(I fixed my global git config uname setting.)

**Comment by cbeams** [comment]
I missed that you had created #46 as well. In any case, if you're going to create a pull request anyway, don't bother with creating an issue too. You can just submit the PR.

And thanks for fixing your Git config. Cheers!
