### ISSUE TITLE
Min trade fee in the FAQ should no longer be 0.0002 BTC?

### ISSUE THREAD

**Issue by dolebas** [bisq-network/bisq-website#47]
Was about to propose a file change here, changing 0.0002 BTC to 0.00005 BTC, but I'm not sure what else might need to be updated.

https://github.com/bisq-network/website/edit/master/faq.html

![image](https://user-images.githubusercontent.com/27515901/37029105-7d45fdd0-2136-11e8-8ba6-dc6d80cc513c.png)

**Comment by ManfredKarrer** [comment]
True its 0.00005 BTC now. Would u like to make the change and a PR?

**Comment by dolebas** [comment]
Would be happy to. Is everything else still accurate, default fee, etc?

**Comment by ManfredKarrer** [comment]
Yes, rest is ok, just min fee has been decreased. Thanks.

**Comment by dolebas** [comment]
Done.

Very tiny PR but, at a philosophical level, the concept of merging into a pioneering DAO is pretty exciting =)

Ps searched the website repo for "0.0002" and it doesn't show any other occurrences that needs to be updated.

**Comment by ManfredKarrer** [comment]
Great thanks!
