### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-website#50]
how do i navigate to the 127.0.0.1:4000, when am on a vps because when i use an ExternalIp:4000 it does not work. I understand the code very well

**Comment by cbeams** [comment]
Please provide more context. Are you running Jekyll locally on your own machine, or actually running it remotely on a VPS? Why would you be running it on a VPS?

`jekyll serve` is just a convenience for development purposes. Jekyll is a static website generator, so if you want to actually serve it from a VPS, you would just serve the HTML and other static assets generated by `jekyll build`.

But again, I wonder why you would want to do this at all. If you want to change something on the Bisq website and submit a pull request back to the project, just do that. If you want to run your own instance of the Bisq website somewhere else on the web, I would frankly be suspicious of your intentions.

**Comment by ghost** [comment]
Ok am just going to stay on it locally, and here is this error
Configuration file: /home/laugh26/bisq-website/_config.yml
            Source: /home/laugh26/bisq-website
       Destination: /home/laugh26/bisq-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html
jekyll 3.5.1 | Error:  invalid byte sequence in US-ASCII

**Comment by cbeams** [comment]
No idea what's causing that. The instructions in the README work fine for me locally (on macOS) and work fine on Netlify, which is *nix-based.

A quick search tells me this is probably some system-specific locale issue on your side. Search for the error messages in question (e.g. like the query below) and you should find solutions to the problem:

https://duckduckgo.com/?q=Liquid+Exception%3A+invalid+byte+sequence+in+US-ASCII&atb=v72-5_y&ia=qa

**Comment by ghost** [comment]
where is this located
image: ruby:2.3

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.ge…

**Comment by cbeams** [comment]
Closing as off-topic. This isn't a Jekyll support forum, and I have no idea whether what you're trying to do is of any value to Bisq / worth my time to answer. Please follow up with questions like this on StackOverflow or elsewhere. Best of luck.
