### ISSUE TITLE
update the blog

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-website#65]
We already had a little discussion about that (on the slack I think).
I believe the blog is important as shop window.
In order to update the blog without too much work, I simply suggest to use the last update 
from https://bisq.network/roadmap/ as the next blog post.
We may wait for v0.7.1 for that. Or group the v0.7.0 and v0.7.1 novelties in one post.
Maybe add 2 or 3 welcome lines, and this would make it imo.
Would be far better than 11 months without anything like now, which certainly confuses some potential customers or contributors. (I was myself confused some months ago).

If there's agreement, I can manage a PR for that.
(I may have proposed directly a PR, but it's probably better to discuss that before.)

**Comment by cbeams** [comment]
@HarryMacfinned, to be clear, when you say the last update from https://bisq.network/roadmap, you mean the latest release announcement, correct?

I think it's fine to republish release notes on the blog. It shows signs of life, is better than nothing, and is easy to do if done correctly.

Better than copying the latest from the roadmap page is to copy the Markdown used on the actual GitHub release at https://github.com/bisq-network/bisq-desktop/releases/tag/v0.7.1. It is better-formatted, and the content is better written there. I've copied and pasted it for you below:

```
## Release notes
This release adds acknowledgment status for trade, offer and dispute messages. This gives the user more information on each message status (message arrived, arrival confirmed, sent to mailbox) during its trade/dispute experience. Besides lots of bug fixes, MoneyGram was added as a new payment method and the account field for Argentinian banks support now non-standard account identifiers. 

### Trading
- [Ack messages for all trade, offer- and dispute messages](https://github.com/bisq-network/bisq-desktop/issues/1585)
- [Add referrer Id for external Bisq market makers](https://github.com/bisq-network/proposals/issues/28)
- [Fix bug in edit offer screen](https://github.com/bisq-network/bisq-desktop/pull/1583) 
- [Remove validation for Argentinian account numbers and allow manual edit](https://github.com/bisq-network/bisq-desktop/pull/1553)
- [Fix bug with Sepa offers and Sepa instant taker](https://github.com/bisq-network/bisq-core/issues/117)
- [Lower minimum withdrawal fee to 1 satoshi per byte](https://github.com/bisq-network/bisq-core/pull/111)
- [Fix reuse of change addresses](https://github.com/bisq-network/bisq-core/pull/113)
- [Don’t treat RBF transactions as risky](https://github.com/bisq-network/bisq-core/pull/124)
- [Fix wrong dust limit values in Bitcoinj](https://github.com/bisq-network/bitcoinj/commit/bbcb39b1c33c61f146265ace94ae54e21e1b8e47)
- [Deactivate Venmo and CashApp](https://github.com/bisq-network/bisq-core/pull/115)

### Payment methods
- Add new payment method: [MoneyGram](https://github.com/bisq-network/bisq-desktop/pull/1522)

### Assets
- Add 28 new assets: 01coin, Aquachain, BitCloud, Bitcoin Core, Bitcoin Instant, Credits, Cryptonodes, CryptoTari, DACash, Diamon, DRIP, FuturoCoin, Graft, LikeCoin, Lobstex, MaxCoin, MegaCoin, MicroCoin, Motion, Myriadcoin, Nano, NewPowerCoin, Nimiq, Pix, PixelPropertyToken, PRiVCY, Triton, Wavi
### UI
- [Add popup for feedback after trade completion](https://github.com/bisq-network/bisq-desktop/issues/1584)
- [Show popup if local Bitcoin core is running](https://github.com/bisq-network/bisq-desktop/issues/1566)
- [Fix wrong duration translation in double digit numbers](https://github.com/bisq-network/bisq-desktop/pull/1552)
- [Fix wrong singular word translation in double digit numbers](https://github.com/bisq-network/bisq-desktop/issues/1549)
- [Fix sorting of currencies in market/trades view](https://github.com/bisq-network/bisq-desktop/pull/1591)

### Development
- [Don’t include assets with diff. network type](https://github.com/bisq-network/bisq-core/pull/129)
- [Ignore “Alert key compromised” message from old nodes in Bitcoinj](https://github.com/bisq-network/bitcoinj/commit/6728ef8bfd685547fe38586302514f2eca6d426c)

Url of the signing key (Christoph Atteneder): https://bisq.network/pubkey/29CDFD3B.asc
Full fingerprint: `CB36 D7D2 EBB2 E35D 9B75  500B CD5D C1C5 29CD FD3B`

How to verify signatures?
`gpg --digest-algo SHA256 --verify BINARY{.asc*,}`
Replace BINARY with the file you downloaded (e.g. Bisq-0.7.1.dmg)

Verify jar file inside binary:
You can verify on OSX the jar file with:
`shasum -a256 [PATH TO BISQ APP]/Bisq.app/Contents/Java/Bisq-0.7.1.jar`
The output need to match the value from the Bisq-0.7.1.jar.txt file.

Hint for Debian users:
If you have problems starting Bisq on Debian use: `/opt/Bisq/Bisq`
```

I would just ask, @HarryMacfinned, that you completely own doing this in the future for each release and/or own making it a part of the regular release process. Thanks, I'll look out for your PR.

**Comment by ghost** [comment]
> to be clear, when you say the last update from https://bisq.network/roadmap, you mean the latest release announcement, correct?

Yes Chris, it's exactly what I meant.
And I was also thinking using the markdown file. I'll prepare a PR. Thanks.

I'm also ok for doing that in the future (... if I do it successfully yet !).

I'll also think about additionnal material for the blog.

**Comment by m52go** [comment]
This commenced with https://github.com/bisq-network/bisq-website/pull/118, and Aruna is leading an effort to sustain the effort. Check [this thread](https://bisq.community/t/call-for-blog-writers/7040) as well as the #blogposts channel on Slack for updates.
