### ISSUE TITLE
Add search engine to the website

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-website#74]
Today we have a nice amount of quality documentation on the website, but no global search engine (or I missed it).
Of course it's always possible to search specifically using Google, but a own search engine could be a help for newbies wanting to learn about this or this precise point/keyword concerning Bisq.

**Comment by cbeams** [comment]
The main website and docs.bisq.network are statically generated sites. This means that integrating a search form, particularly a custom search form i.e. one for which we maintain and query our own index, etc, is not practical.

Integrating a Google custom site search form would be easy though, and is usually the sort of thing that static sites do, if they do anything at all.

DuckDuckGo and other privacy conscious search engines may offer similar functionality, I took a quick look at DDG though and didn’t see anything. In any case, I would recommend the following:

- loop @pedromvpg in on the design
- any search form on the main site should include results from the docs site as well
- keep it simple

And honestly, if it’s not dead simple, I wouldn’t do anything. Many static sites get by without dedicated search. People in our current audience probably know how to type “site:bisq.network <term>” into Google or DDG and get the results they want. The key thing is to go with the flow of a static site, and not try too get too fancy with anything.

**Comment by m52go** [comment]
It seems like the opening post is referring to documentation:

> Today we have a nice amount of quality documentation on the website

Documentation can certainly use a search function, and ways to accomplish it are being discussed in https://github.com/bisq-network/bisq-docs/issues/131.
