### ISSUE TITLE
Add doc for F2F trading

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#78]
For the upcoming release (prob. 20. Aug.) we need an entry in the docs page for the rules and description for F2F trade.
We discussed a bit here: https://github.com/bisq-network/bisq-desktop/pull/1607

@m52go Do you have time to work on that?  We can start with a minimal version and update later to a more extended version (e.g. recommendations like on LocalBitcoins)

**Comment by m52go** [comment]
This one's on my list, but in that thread it was suggested that we integrate F2F Rules into the overall Rules doc, which hasn't been written yet. So it's a big job...that I can't do before August 20.

Unless it would be okay to just do F2F for now and put placeholders for everything else--then I could possibly get something done soon.

**Comment by cbeams** [comment]
> On Aug 16, 2018, at 8:38 PM, Steve Jain <notifications@github.com> wrote:
> 
> Unless it would be okay to just do F2F for now and put placeholders for everything else--then I could possibly get something done soon.

+1. Placeholders can be link to existing FAQ entries.

**Comment by m52go** [comment]
Thanks @cbeams. Per your comment [here](https://github.com/bisq-network/bisq-desktop/pull/1607#issuecomment-407454450), are there any other places where Rules are documented aside from the FAQs? I'm sure some stuff is scattered through reddit/forum posts, which I can search for as needed.

**Comment by cbeams** [comment]
My bad. There actually are no FAQ sections that deal with trading and arbitration rules.

In fact, to my knowledge, there is no place we capture them except here:

https://github.com/bisq-network/bisq-desktop/wiki/3.4.-Arbitration-system

@ManfredKarrer please correct me if I'm wrong.

So you can:

 - carry over these few rules from the wiki into a general section of a new `trading-rules.adoc` that will fill in the `Trading and Arbitration Rules` placeholder on `index.adoc`
 - remove the entries from the wiki and link to the new doc (when it's published)
 - Add a #f2f-trading section to the `trading-rules.adoc` file that goes into whatever detail necessary.

The whole link to F2F trading rules would read as follows:

> https://docs.bisq.network/trading-rules.html#f2f-trading

**Comment by cbeams** [comment]
And as an aside, it would be good to do these issues in the bisq-docs repository in the future, instead of here in the bisq-website repository.

**Comment by ManfredKarrer** [comment]
I am also not aware of another place of rules. Maybe the user agreement in the app is relevant as well.
```
1. In no event, unless for damages caused by acts of intent and gross negligence, damages resulting from personal injury, " +
                "or damages ensuing from other instances where liability is required by applicable law or agreed to in writing, will any " +
                "developer, copyright holder and/or any other party who modifies and/or conveys the software as permitted above or " +
                "facilitates its operation, be liable for damages, including any general, special, incidental or consequential damages " +
                "arising out of the use or inability to use the software (including but not limited to loss of data or data being " +
                "rendered inaccurate or losses sustained by you or third parties or a failure of the software to operate with any " +
                "other software), even if such developer, copyright holder and/or other party has been advised of the possibility of such damages.\n\n" +

                "2. The user is responsible to use the software in compliance with local laws. Don't use the software if the usage is not legal in your jurisdiction.\n\n" +

                "3. The " + Res.getBaseCurrencyName() + " market price is delivered by 3rd parties (BitcoinAverage, Poloniex, Coinmarketcap). " +
                "It is your responsibility to verify the price with other sources for correctness.\n\n" +

                "4. Any Fiat payment method carries a potential risk for bank chargeback. By accepting the \"User Agreement\" the users confirms " +
                "to be aware of those risks and in no case will claim legal responsibility to the authors or copyright holders of the software.\n\n" +

                "5. Any dispute, controversy or claim arising out of or relating to the use of the software shall be settled by arbitration in " +
                "accordance with the Bisq arbitration rules as at present in force. The arbitration is conducted online. " +
                "The language to be used in the arbitration proceedings shall be English if not otherwise stated.\n\n" +

                "6. The user confirms that he has read and agreed to the rules regarding the dispute process:\n" +
                "    - You must complete trades within the maximum duration specified for each payment method.\n" +
                "    - You must enter the trade ID in the \"reason for payment\" text field when doing the fiat payment transfer.\n" +
                "    - If the bank of the fiat sender charges fees the sender (" + Res.getBaseCurrencyCode() + " buyer) has to cover the fees.\n" +
                "    - You must cooperate with the arbitrator during the arbitration process.\n" +
                "    - You must reply within 48 hours to each arbitrator inquiry.\n" +
                "    - Failure to follow the above requirements may result in loss of your security deposit.\n\n" +
                "For more details and a general overview please read the full documentation about the " +
                "arbitration system and the dispute process.
```

**Comment by ManfredKarrer** [comment]
@m52go We will likely release today (in a few hours). Could you add some PR for a preliminary text (placeholder) in case you have not completed the text? We can update then the next days, just to have not a "page not found"...

**Comment by m52go** [comment]
@ManfredKarrer yup.

**Comment by m52go** [comment]
I created [this issue](https://github.com/bisq-network/bisq-docs/issues/80) to discuss the whole Rules doc, F2F included. Moving forward let's move all discussion related to that doc over there.

**Comment by m52go** [comment]
Superceded by https://github.com/bisq-network/bisq-docs/issues/80. Closing.
