### ISSUE TITLE
Add doc for Mobile notifications

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#79]
For the upcoming release (prob. 20. Aug.) we need an entry in the docs page for the Mobile notifications.

I suggested content for a text here:
https://github.com/bisq-network/bisq-desktop/issues/1622#issuecomment-413169865

@m52go Do you have time to work on that?

**Comment by m52go** [comment]
Hey @ManfredKarrer, yes I'll get this done before August 20.

**Comment by ManfredKarrer** [comment]
Great thanks! And sorry for the short notice...

**Comment by m52go** [comment]
@ManfredKarrer @cbeams is there a placeholder for this doc already in `index.adoc`? I see this:

> Bisq Mobile — Operate your Bisq node remotely via a web/mobile frontend

Is this part of the same initiative?

If not, let me know if this is any good:

- new doc at `mobile-notifications.adoc`
- create link at bottom of Features section (make it the third one) that looks something like this:

Mobile Notifications — *Get alerts for new offers, trades in process, and more right on your phone.*

**Comment by cbeams** [comment]
Very good catch asking about this @m52go. Thank you.

Yes, the Bisq Mobile placeholder on `index.adoc` refers to this same overall effort.

It would therefore be better to maintain a single doc, and have the link in question here read as follows:

> https://docs.bisq.network/bisq-mobile.html#notifications

The doc title would be "Bisq Mobile" as it is in the placeholder.

You can add an admonition at the top the doc that explains it is a work in progress.

The #notification section would a second-level heading that reads as you see fit per earlier conversations with Manfred.

@ManfredKarrer, you would need to update and test the redirect to make sure that the #notifications fragment comes through in the 302 (I remember there may have been a limitation with this). You could leave the redirect as /mobile-notifications if you like.

**Comment by m52go** [comment]
Ah thanks for clarifying! I would've guessed otherwise.

**Comment by ManfredKarrer** [comment]
@m52go Regarding the plans for a full mobile app:

There is work in progress from Bernard for a mobile app which connects to the users Bisq app (desktop or headless on a server) via the HTTP API. This version seems to be very feature complete from most Bisq featues. 
Joachim might continue to work on a lightweight mobile app for bi-directional communication (the notification is only Bisq app to Mobile). That would be  Tor hidden service on the mobile which connects to Bisq via an API. But it is not decided yet that he will go working on that. Will be a bigger effort for sure and might be that it only works for Android as Tor on iOS is problematic.

**Comment by ManfredKarrer** [comment]
@cbeams I just merged the redirect to the new URL and it works (though Page Not found atm).

**Comment by cbeams** [comment]
Sorry, I should have been müde clear here. At this point the larger effort is “Bisq Remote” (not “Bisq Mobile”). The notifications we’re talking about are from Bisq Remote—just this very lightweight integration, please confirm, Manfred. So we souls keep it all on a dedicated page, but the page can revolve around Remote, not Mobile.

Sorry für the runaround @m52go. I’m mostly doing this from my phone...

**Comment by ManfredKarrer** [comment]
Hm... we don't have a clear naming for the 3 potential mobile apps.
1. Bisq mobile notifications which we have now ready. In the app stores it is called just Bisq atm. Open question what should be the name. Author is @joachimneumann 
2. There is WIP project from @blabno for a full features Bisq mobile app using the HTTP API.
3. There is a rough idea that @joachimneumann continues to work on a mobile app which use tor hidden services on the mobile to talk to Bisq via a not yet specified API. The intention here is not to provide a fully featured Bisq app but to focus on the minimal set to be useful for trading, thus having easier usability as less complexity/information need to be presented in the mobile app. So it will have a different approach to the version of @blabno. But as said no work started on that and its an open question if we should provide 2 apps which serve a similar purpose. 

Not sure if we should try to fix the names already now or just do it once a project gets ready to be deployed? Maybe we should call it internally:
1. Bisq (mobile) notifications
2. Bisq mobile
3. Bisq remote

But no strong opinions here... we just need to be sure to not confuse the different approaches.

**Comment by cbeams** [comment]
Ugh. I've made a mess of this, and responded too hastily before. Thanks for clarifying, Manfred. Please go back to the original doc name and plan. When the fuller apps get fleshed out, then we can revisit this. @m52go, please replace the placeholder on index for "Bisq Mobile" with "Bisq Mobile Notifications", linking to  /mobile-notifications.html as originally planned. I'll stay out of this topic now.

**Comment by m52go** [comment]
Alrighty! Thank you both.

**Comment by ManfredKarrer** [comment]
@m52go We will likely release today (in a few hours). Could you add some PR for a preliminary text (placeholder) in case you have not completed the text? We can update then the next days, just to have not a "page not found"...

**Comment by m52go** [comment]
Completed with https://github.com/bisq-network/bisq-docs/pull/79.
