### ISSUE TITLE
Add download links to mobile notification apps at Apple and Gogle Play store 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-website#80]
For the upcoming release (prob. 20. Aug.) we need to add the download links for the Mobile notifications apps to our download page. It has to be static html without javascript.

@joachimneumann Can you work on that?

**Comment by ManfredKarrer** [comment]
@ripcurlx Could you add the links? The Android link should be available soon, the iOS link should contain (or link to) a text that Apple is still reviewing the app.

**Comment by m52go** [comment]
Completed with #83 and #84.
