### ISSUE TITLE
Download drop-down list is misaligned

### ISSUE THREAD

**Issue by bugrasan** [bisq-network/bisq-website#88]
system details:
FF 62.0.3
ubuntu 18.04

test site: https://pedromvpg.github.io/bisq-website/

see screenshot:
![image](https://user-images.githubusercontent.com/8294295/46866902-75c7b680-ce23-11e8-9eb0-0094424014bd.png)

same with top menu download links:
![image](https://user-images.githubusercontent.com/8294295/46866991-c17a6000-ce23-11e8-97db-0cbec914a9dc.png)

**Comment by pedromvpg** [comment]
@bugrasan can you check if this is fixed? When I force this to detect Linux it works for me. 
Can you also send a full browser screenshot so I can check the width of your window?

![screen shot 2018-10-16 at 1 20 11 am](https://user-images.githubusercontent.com/807505/46994257-b48a9480-d0e1-11e8-8574-95be3f4e31e9.png)
![screen shot 2018-10-16 at 1 19 28 am](https://user-images.githubusercontent.com/807505/46994258-b48a9480-d0e1-11e8-9264-8fa95b5e8e5b.png)

**Comment by bugrasan** [comment]
taken with FF screenshot:

![image](https://user-images.githubusercontent.com/8294295/47001512-eaa03680-d12a-11e8-8197-2a68bc00aac2.png)


![image](https://user-images.githubusercontent.com/8294295/47001491-df4d0b00-d12a-11e8-919d-49ecee7fbcf4.png)

**Comment by m52go** [comment]
Thanks for reporting, closing as complete.
