### ISSUE TITLE
Get Android Notifications App text and icon are overlapped

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq-website#89]
Android 7.0
Firefox 61.0.2

![screenshot_20181016_095429](https://user-images.githubusercontent.com/14953828/47000953-b9733680-d129-11e8-9752-b59dec34b6f6.png)

**Comment by m52go** [comment]
Thanks for reporting. This was fixed through a series of commits by @pedromvpg and #97, #99, and/or #102.
